version: '3.8'

services:
  whatsapp-otp-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Gupshup WhatsApp API Configuration
      - GUPSHUP_API_KEY=${GUPSHUP_API_KEY}
      - GUPSHUP_SOURCE=${GUPSHUP_SOURCE}
      - GUPSHUP_TEMPLATE_ID=${GUPSHUP_TEMPLATE_ID}
      - GUPSHUP_SRC_NAME=${GUPSHUP_SRC_NAME}
      - GUPSHUP_API_URL=${GUPSHUP_API_URL:-https://api.gupshup.io/wa/api/v1/template/msg}
      
      # Supabase Configuration
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      
      # OTP Configuration
      - OTP_EXPIRY_MINUTES=${OTP_EXPIRY_MINUTES:-3}
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - otp-network

networks:
  otp-network:
    driver: bridge 